// Medical specialties
export const SPECIALTIES = [
  { id: '1', name: 'General Physician', icon: '🩺' },
  { id: '2', name: 'Pediatrician', icon: '👶' },
  { id: '3', name: 'Cardiologist', icon: '❤️' },
  { id: '4', name: 'Dermatologist', icon: '✨' },
  { id: '5', name: 'Gynecologist', icon: '👩‍⚕️' },
  { id: '6', name: 'Orthopedic', icon: '🦴' },
  { id: '7', name: 'Dentist', icon: '🦷' },
  { id: '8', name: 'ENT Specialist', icon: '👂' },
  { id: '9', name: 'Skin & Hair', icon: '💆' },
  { id: '10', name: "Women's Health", icon: '🤰' },
  { id: '11', name: 'Dental care', icon: '🦷' },
  { id: '12', name: 'Bones & Joints', icon: '🦴' },
  { id: '13', name: 'Mental Wellness', icon: '🧠' },
  { id: '14', name: 'Ear, Nose, Throat', icon: '👃' },
  { id: '15', name: 'Sexual Health', icon: '❤️' },
  { id: '16', name: 'Child Specialist', icon: '👶' },
  { id: '17', name: 'Homeopathy', icon: '💊' },
  { id: '18', name: 'Digestive Issues', icon: '🫃' },
  { id: '19', name: 'Eye Specialist', icon: '👁️' },
  { id: '20', name: 'Heart', icon: '💓' },
  { id: '21', name: 'Physiotherapy', icon: '🏃' },
  { id: '22', name: 'Brain and Nerves', icon: '🧠' },
  { id: '23', name: 'Lungs and Breathing', icon: '🫁' },
  { id: '24', name: 'Kidney Issues', icon: '🫘' },
  { id: '25', name: 'General Surgery', icon: '🏥' },
  { id: '26', name: 'Diabetes Management', icon: '💉' },
];

// Dummy doctors data with real images
export const DUMMY_DOCTORS = [
  {
    id: "1",
    name: "Dr. Rajesh Kumar",
    specialty: "General Physician",
    qualification: "MBBS, MD",
    experience: 15,
    rating: 4.8,
    reviews: 245,
    consultationFee: 500,
    hospital: "Nabha Civil Hospital",
    city: "Nabha",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    availableSlots: ["10:00 AM", "11:00 AM", "2:00 PM", "4:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "2",
    name: "Dr. Priya Sharma",
    specialty: "Pediatrician",
    qualification: "MBBS, MD (Pediatrics)",
    experience: 10,
    rating: 4.9,
    reviews: 189,
    consultationFee: 600,
    hospital: "Max Super Specialty Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    availableSlots: ["9:00 AM", "11:30 AM", "3:00 PM", "5:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "3",
    name: "Dr. Amarjeet Singh",
    specialty: "Cardiologist",
    qualification: "MBBS, MD, DM (Cardiology)",
    experience: 20,
    rating: 4.7,
    reviews: 312,
    consultationFee: 800,
    hospital: "Fortis Hospital",
    city: "Mohali",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    availableSlots: ["10:30 AM", "12:00 PM", "3:30 PM"],
    nextAvailable: "Today",
  },
  {
    id: "4",
    name: "Dr. Neha Verma",
    specialty: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    experience: 8,
    rating: 4.6,
    reviews: 156,
    consultationFee: 550,
    hospital: "Nabha Civil Hospital",
    city: "Nabha",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    availableSlots: ["11:00 AM", "1:00 PM", "4:00 PM", "6:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "5",
    name: "Dr. Harpreet Kaur",
    specialty: "Gynecologist",
    qualification: "MBBS, MS (OB-GYN)",
    experience: 12,
    rating: 4.8,
    reviews: 201,
    consultationFee: 650,
    hospital: "Civil Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    availableSlots: ["9:30 AM", "12:30 PM", "3:00 PM", "5:30 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "6",
    name: "Dr. Suresh Patel",
    specialty: "Orthopedic",
    qualification: "MBBS, MS (Orthopedics)",
    experience: 18,
    rating: 4.7,
    reviews: 278,
    consultationFee: 700,
    hospital: "Apollo Hospital",
    city: "Ludhiana",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/62.jpg",
    availableSlots: ["10:00 AM", "1:00 PM", "4:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "7",
    name: "Dr. Kavita Reddy",
    specialty: "Pediatrician",
    qualification: "MBBS, MD (Pediatrics)",
    experience: 14,
    rating: 4.9,
    reviews: 267,
    consultationFee: 600,
    hospital: "Nabha Civil Hospital",
    city: "Nabha",
    languages: ["English", "Hindi", "Telugu"],
    image: "https://randomuser.me/api/portraits/women/79.jpg",
    availableSlots: ["8:30 AM", "11:00 AM", "2:30 PM", "5:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "8",
    name: "Dr. Vikram Malhotra",
    specialty: "ENT Specialist",
    qualification: "MBBS, MS (ENT)",
    experience: 16,
    rating: 4.6,
    reviews: 198,
    consultationFee: 650,
    hospital: "Fortis Hospital",
    city: "Mohali",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/71.jpg",
    availableSlots: ["9:00 AM", "12:00 PM", "3:00 PM", "6:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "9",
    name: "Dr. Anjali Desai",
    specialty: "Dermatologist",
    qualification: "MBBS, MD (Dermatology)",
    experience: 11,
    rating: 4.8,
    reviews: 223,
    consultationFee: 700,
    hospital: "Max Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Gujarati"],
    image: "https://randomuser.me/api/portraits/women/85.jpg",
    availableSlots: ["10:00 AM", "1:30 PM", "4:30 PM"],
    nextAvailable: "Today",
  },
  {
    id: "10",
    name: "Dr. Rajeev Gupta",
    specialty: "General Physician",
    qualification: "MBBS, MD",
    experience: 22,
    rating: 4.7,
    reviews: 341,
    consultationFee: 450,
    hospital: "Civil Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/83.jpg",
    availableSlots: ["8:00 AM", "10:30 AM", "2:00 PM", "5:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "11",
    name: "Dr. Meera Iyer",
    specialty: "Cardiologist",
    qualification: "MBBS, MD, DM (Cardiology)",
    experience: 17,
    rating: 4.9,
    reviews: 289,
    consultationFee: 850,
    hospital: "Apollo Hospital",
    city: "Ludhiana",
    languages: ["English", "Hindi", "Tamil"],
    image: "https://randomuser.me/api/portraits/women/91.jpg",
    availableSlots: ["11:00 AM", "2:00 PM", "4:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "12",
    name: "Dr. Sandeep Khanna",
    specialty: "Orthopedic",
    qualification: "MBBS, MS (Orthopedics)",
    experience: 19,
    rating: 4.8,
    reviews: 312,
    consultationFee: 750,
    hospital: "Fortis Hospital",
    city: "Mohali",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/91.jpg",
    availableSlots: ["9:30 AM", "12:30 PM", "4:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "13",
    name: "Dr. Pooja Menon",
    specialty: "Gynecologist",
    qualification: "MBBS, MS (OB-GYN)",
    experience: 13,
    rating: 4.7,
    reviews: 234,
    consultationFee: 600,
    hospital: "Max Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Malayalam"],
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    availableSlots: ["10:00 AM", "1:00 PM", "3:30 PM", "6:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "14",
    name: "Dr. Arjun Kapoor",
    specialty: "Dentist",
    qualification: "BDS, MDS",
    experience: 9,
    rating: 4.6,
    reviews: 176,
    consultationFee: 500,
    hospital: "Smile Dental Clinic",
    city: "Nabha",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    availableSlots: ["9:00 AM", "11:30 AM", "2:30 PM", "5:30 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "15",
    name: "Dr. Shreya Nair",
    specialty: "Eye Specialist",
    qualification: "MBBS, MS (Ophthalmology)",
    experience: 12,
    rating: 4.8,
    reviews: 198,
    consultationFee: 650,
    hospital: "Vision Eye Care",
    city: "Patiala",
    languages: ["English", "Hindi", "Malayalam"],
    image: "https://randomuser.me/api/portraits/women/54.jpg",
    availableSlots: ["10:30 AM", "1:00 PM", "4:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "16",
    name: "Dr. Manish Joshi",
    specialty: "General Surgery",
    qualification: "MBBS, MS (Surgery)",
    experience: 21,
    rating: 4.7,
    reviews: 356,
    consultationFee: 800,
    hospital: "Apollo Hospital",
    city: "Ludhiana",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/56.jpg",
    availableSlots: ["11:00 AM", "3:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "17",
    name: "Dr. Lakshmi Pillai",
    specialty: "Physiotherapy",
    qualification: "BPT, MPT",
    experience: 8,
    rating: 4.6,
    reviews: 142,
    consultationFee: 450,
    hospital: "Rehab Center",
    city: "Patiala",
    languages: ["English", "Hindi", "Tamil"],
    image: "https://randomuser.me/api/portraits/women/63.jpg",
    availableSlots: ["8:00 AM", "10:00 AM", "2:00 PM", "4:00 PM", "6:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "18",
    name: "Dr. Rohit Agarwal",
    specialty: "Diabetes Management",
    qualification: "MBBS, MD (Endocrinology)",
    experience: 14,
    rating: 4.8,
    reviews: 267,
    consultationFee: 700,
    hospital: "Fortis Hospital",
    city: "Mohali",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/78.jpg",
    availableSlots: ["9:30 AM", "12:00 PM", "3:30 PM"],
    nextAvailable: "Today",
  },
  {
    id: "19",
    name: "Dr. Divya Saxena",
    specialty: "Mental Wellness",
    qualification: "MBBS, MD (Psychiatry)",
    experience: 11,
    rating: 4.9,
    reviews: 221,
    consultationFee: 750,
    hospital: "Mind Care Clinic",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    availableSlots: ["10:00 AM", "2:00 PM", "4:00 PM", "6:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "20",
    name: "Dr. Karan Bhatia",
    specialty: "Digestive Issues",
    qualification: "MBBS, MD (Gastroenterology)",
    experience: 16,
    rating: 4.7,
    reviews: 289,
    consultationFee: 800,
    hospital: "Max Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/67.jpg",
    availableSlots: ["11:00 AM", "1:30 PM", "4:30 PM"],
    nextAvailable: "Today",
  },
  {
    id: "21",
    name: "Dr. Ritu Choudhary",
    specialty: "Homeopathy",
    qualification: "BHMS, MD (Homeopathy)",
    experience: 10,
    rating: 4.5,
    reviews: 167,
    consultationFee: 400,
    hospital: "Homeo Care Clinic",
    city: "Nabha",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/women/89.jpg",
    availableSlots: ["9:00 AM", "12:00 PM", "3:00 PM", "5:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "22",
    name: "Dr. Aditya Rao",
    specialty: "Lungs and Breathing",
    qualification: "MBBS, MD (Pulmonology)",
    experience: 15,
    rating: 4.8,
    reviews: 243,
    consultationFee: 750,
    hospital: "Apollo Hospital",
    city: "Ludhiana",
    languages: ["English", "Hindi", "Telugu"],
    image: "https://randomuser.me/api/portraits/men/89.jpg",
    availableSlots: ["10:00 AM", "1:00 PM", "4:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "23",
    name: "Dr. Swati Banerjee",
    specialty: "Kidney Issues",
    qualification: "MBBS, MD, DM (Nephrology)",
    experience: 13,
    rating: 4.7,
    reviews: 201,
    consultationFee: 850,
    hospital: "Fortis Hospital",
    city: "Mohali",
    languages: ["English", "Hindi", "Bengali"],
    image: "https://randomuser.me/api/portraits/women/95.jpg",
    availableSlots: ["11:30 AM", "2:30 PM", "5:00 PM"],
    nextAvailable: "Today",
  },
  {
    id: "24",
    name: "Dr. Naveen Kumar",
    specialty: "Brain and Nerves",
    qualification: "MBBS, MD, DM (Neurology)",
    experience: 18,
    rating: 4.9,
    reviews: 312,
    consultationFee: 900,
    hospital: "Max Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/95.jpg",
    availableSlots: ["10:00 AM", "2:00 PM", "4:00 PM"],
    nextAvailable: "Tomorrow",
  },
  {
    id: "25",
    name: "Dr. Deepika Ghosh",
    specialty: "Child Specialist",
    qualification: "MBBS, MD (Pediatrics)",
    experience: 12,
    rating: 4.8,
    reviews: 234,
    consultationFee: 600,
    hospital: "Civil Hospital",
    city: "Patiala",
    languages: ["English", "Hindi", "Bengali"],
    image: "https://randomuser.me/api/portraits/women/36.jpg",
    availableSlots: ["8:30 AM", "11:00 AM", "3:00 PM", "5:30 PM"],
    nextAvailable: "Today",
  },
  {
    id: "26",
    name: "Dr. Ashish Verma",
    specialty: "General Physician",
    qualification: "MBBS, MD",
    experience: 7,
    rating: 4.5,
    reviews: 134,
    consultationFee: 400,
    hospital: "Nabha Civil Hospital",
    city: "Nabha",
    languages: ["English", "Hindi", "Punjabi"],
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    availableSlots: ["9:00 AM", "12:00 PM", "3:00 PM", "6:00 PM"],
    nextAvailable: "Today",
  },
];

// Health record categories
export const RECORD_CATEGORIES = [
  { id: '1', name: 'Lab Report', icon: '🔬' },
  { id: '2', name: 'Prescription', icon: '💊' },
  { id: '3', name: 'Medical Imaging', icon: '📊' },
  { id: '4', name: 'Vaccination', icon: '💉' },
  { id: '5', name: 'Medical Bill', icon: '💰' },
];


// Dummy medicines data
export const DUMMY_MEDICINES = [
  {
    id: "1",
    name: "Paracetamol 500mg",
    category: "Pain Relief",
    price: 20,
    available: true,
    pharmacies: [
      { name: "Apollo Pharmacy", distance: "2 km", stock: "In Stock" },
      { name: "MedPlus", distance: "3.5 km", stock: "In Stock" },
    ],
  },
  {
    id: "2",
    name: "Amoxicillin 250mg",
    category: "Antibiotic",
    price: 80,
    available: true,
    pharmacies: [
      { name: "Wellness Pharmacy", distance: "1.5 km", stock: "In Stock" },
      { name: "HealthCare Pharmacy", distance: "4 km", stock: "Low Stock" },
    ],
  },
  {
    id: "3",
    name: "Cetirizine 10mg",
    category: "Allergy",
    price: 35,
    available: true,
    pharmacies: [
      { name: "Apollo Pharmacy", distance: "2 km", stock: "In Stock" },
    ],
  },
];
